spring:
  application:
    name: LogisticApp
  datasource:
    url: jdbc:postgresql://localhost:5432/logistic
    username: postgres
    password: nemmondommeg
  jpa:
    hibernate:
      ddl-auto: update

logistic:
  delay:
    min30: 1
    min60: 2
    min120: 5
